# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript
trigger:
- main

variables:
- group: ItSnippetsVariables
- name: environment
  value: dev
- name: linuxFxVersion
  value: NODE|12-lts
- name: angularProjectName
  value: blog-ng-client
- name: projectName
  value: BlogClientApp
- name: projectPath
  value: 'source/WebUI/$(projectName)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
      displayName: 'Install packages'
      workingDirectory: '$(projectPath)'

    - script: |
        ng lint
      displayName: 'Run linter'
      workingDirectory: '$(projectPath)'

    - script: |
        npm run test-headless
      displayName: 'Run tests'
      workingDirectory: '$(projectPath)'

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TESTS-*.xml'
      displayName: 'Publish test results'

    - script: |
        ng build --prod
      displayName: 'Build for prod'
      workingDirectory: '$(projectPath)'
    
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'deploy'
        Contents: '*.json'
        TargetFolder: '$(projectPath)/dist/blog-ng-client'

    - task: ArchiveFiles@2
      inputs:        
        rootFolderOrFile: '$(projectPath)/dist/blog-ng-client'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: '$(projectName)'
        publishLocation: 'Container'

- stage: Deploy
  displayName: 'Deploy '
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeploymentJob
    pool:
      vmImage: 'ubuntu-20.04'
    environment: '$(environment)'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureAppServiceManage@0
            displayName: 'Stop app'
            continueOnError: true
            inputs:
              azureSubscription: '$(armServiceConnectionName)'
              Action: 'Stop Azure App Service'
              WebAppName: '$(applicationName)$(environment)'
          - task: replacetokens@3
            inputs:
              targetFiles: '$(System.WorkFolder)/dist/**/main*.js'
              encoding: 'auto'
              writeBOM: true
              verbosity: 'detailed'
              actionOnMissing: 'warn'
              keepToken: false
              tokenPrefix: '#{'
              tokenSuffix: '}#'
              useLegacyPattern: false
              enableTransforms: false
              enableTelemetry: false

          - task: ExtractFiles@1
            inputs:
              archiveFilePatterns: '$(System.WorkFolder)/**/*.zip'
              destinationFolder: '$(System.WorkFolder)'
              cleanDestinationFolder: false
              overwriteExistingFiles: true
          - task: AzureResourceManagerTemplateDeployment@3
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(armServiceConnectionName)'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: '$(applicationName)$(environment)'
              location: '$(location)'
              templateLocation: 'Linked artifact'
              csmFile: '$(System.WorkFolder)/blog-client-app-template.json'
              csmParametersFile: '$(System.WorkFolder)/blog-client-app-parameters.json'
              overrideParameters: '-location "$(location)" -subscriptionId "$(subscriptionId)" -name "$(applicationName)$(environment)" -hostingPlanName "$(servicePlanName)" -serverFarmResourceGroup "$(serverPlanResourceGroup)" -linuxFxVersion "$(linuxFxVersion)"'
              deploymentMode: 'Incremental'

          - task: AzureWebApp@1
            inputs:
              azureSubscription: '$(armServiceConnectionName)'
              appType: 'webAppLinux'
              appName: '$(applicationName)$(environment)'
              package: '$(System.WorkFolder)/**/$(projectName)/*.zip'
              runtimeStack: '$(linuxFxVersion)'
              startUpCommand: 'pm2 serve /home/site/wwwroot --no-daemon --spa'
          
          - task: AzureAppServiceManage@0
            displayName: 'Start app'
            inputs:
              azureSubscription: '$(armServiceConnectionName)'
              Action: 'Start Azure App Service'
              WebAppName: '$(applicationName)$(environment)'