# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
- name: ProjectName
  value: blog-ng-client
- name: ProjectFolder
  value: 'source/${ProjectName}'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'

    - script: |
        npm install -g @angular/cli
        npm install
      displayName: 'Install packages'
      workingDirectory: '${ProjectFolder}''

    - script: |
        ng lint
      displayName: 'Run linter'
      workingDirectory: '${ProjectFolder}''

    - script: |
        npm run test-headless
      displayName: 'Run tests'
      workingDirectory: '${ProjectFolder}''

    - task: PublishTestResults@2
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TESTS-*.xml'
      displayName: 'Publish test results'

    - script: |
        ng build --prod
      displayName: 'Build for prod'
      workingDirectory: '${ProjectFolder}''

    - task: ArchiveFiles@2
      inputs:        
        rootFolderOrFile: '${ProjectFolder}/dist/${ProjectName}'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: '${ProjectName}'
        publishLocation: 'Container'
