# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-16.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'
  workingDirectory: source/blog-ng-client

- script: |
    ng lint
  displayName: 'ng lint'
  workingDirectory: source/blog-ng-client

- script: |
    npm run test-headless
  displayName: 'ng test'
  workingDirectory: source/blog-ng-client

- script: |
    ng build --prod
  displayName: 'ng build'
  workingDirectory: source/blog-ng-client
