# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-16.04

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Install packages'
  workingDirectory: source/blog-ng-client

- script: |
    ng lint
  displayName: 'Run linter'
  workingDirectory: source/blog-ng-client

- script: |
    npm run test-headless
  displayName: 'Run tests'
  workingDirectory: source/blog-ng-client

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'
  displayName: 'Publish Test Results'

- script: |
    ng build --prod
  displayName: 'Build for prod'
  workingDirectory: source/blog-ng-client
