trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: ItSnippetsVariables

steps:
  - task: CmdLine@2
    inputs:
      script: 'echo $(servicePlanLinuxName)'

  - template: 'PipelineTemplates/service-plan-template.yaml'
    parameters:
      armServiceConnectionName: $(armServiceConnectionName)
      subscriptionId: $(subscriptionId)
      serverPlanResourceGroup: $(serverPlanResourceGroup)
      location: $(location)
      csmFile: '**/linux-service-plan-template.json'
      csmParametersFile: '**/linux-service-plan-parameters.json'
      servicePlanName: $(servicePlanLinuxName)
  
  - task: CmdLine@2
    inputs:
      script: 'echo $(servicePlanWindowsName)'

  - template: 'PipelineTemplates/service-plan-template.yaml'
    parameters:
      armServiceConnectionName: $(armServiceConnectionName)
      subscriptionId: $(subscriptionId)
      serverPlanResourceGroup: $(serverPlanResourceGroup)
      location: $(location)
      csmFile: '**/windows-service-plan-template.json'
      csmParametersFile: '**/windows-service-plan-parameters.json'
      servicePlanName: $(servicePlanWindowsName)
