# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
- group: ItSnippetsVariables

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: '$(armServiceConnectionName)'
    subscriptionId: '$(subscriptionId)'
    action: 'Create Or Update Resource Group'
    resourceGroupName: '$(serverPlanResourceGroup)'
    location: '$(location)'
    templateLocation: 'Linked artifact'
    csmFile: 'deploy/service-plan-template.json'
    csmParametersFile: 'deploy/service-plan-parameters.json'
    overrideParameters: '-name $(servicePlanName) -location $(location)'
    deploymentMode: 'Incremental'
